### ISSUE TITLE
[Request] port to RetroArch

### ISSUE THREAD

**Issue by Cibomatto2002** [NovaSquirrel/Mesen-X#107]
Is there any plans to port this to RetroArch?

**Comment by jeffythedragonslayer** [comment]
NovaSquirrel let me know on discord that the work on her fork is complete.  You could join us in #emulator-dev in https://discord.gg/37dyhHB5 if you want to help out improving Mesen-X.

**Comment by negativeExponent** [comment]
You should be able to build libretro cores directly for Linux from this repo

**Comment by Cibomatto2002** [comment]
ok thanks
