### ISSUE TITLE
Mapper 28 (Action 53) seems to initialize wrong

### ISSUE THREAD

**Issue by NovaSquirrel** [NovaSquirrel/Mesen-X#6]
Action 53's mapper [should](http://wiki.nesdev.com/w/index.php/Action_53_mapper#Power_up_state) power up with $c000-$ffff mapped to the last 16KB of the ROM. However, Mesen initializes all mapper registers to zero, so as soon as `UpdateState()` gets called, the first 16KB is put in $c000-$ffff because of a zero outer bank.

**Comment by negativeExponent** [comment]
REGS have to be initialized to 0xff, then call UpdateState() in init instead of SelectPrgPage()
