### ISSUE TITLE
Save state Error

### ISSUE THREAD

**Issue by Sayori1576** [NovaSquirrel/Mesen-X#91]
When I closed program and load to last state, program crashed.

**Comment by Sayori1576** [comment]
Kirby's adventure does same.

**Comment by Sayori1576** [comment]
No, **All Game Does Same**

**Comment by NovaSquirrel** [comment]
This sounds like #70 - I guess I should go publish a more recent build

**Comment by negativeExponent** [comment]
what do you mean "close program and load to last state", what state are you loading without reopening the rom you are gonna play with?

and what exactly is "load to last state"? there is Load State, and Load Last Session where it load the game directly from where you left off.. which both worked on linux fine.

**Comment by negativeExponent** [comment]
dont close and unresolved issue
